name: first_assignment
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  test:
  json_annotation: ^4.4.0

dev_dependencies:
  lints: ^1.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0